apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 65.5.1        # pin; bump via Renovate later
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/infra/gitops/monitoring/kube-prometheus-stack.values.yaml
    - repoURL: https://github.com/ravin00/AFIE.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true