apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-07-01T10:03:32Z"
    labels:
      kubernetes.io/metadata.name: afie-system
    name: afie-system
    resourceVersion: "1409"
    uid: 5bf002bf-1d0d-4f19-9034-4deb2de1d9ef
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-07-01T10:03:32Z"
    labels:
      kubernetes.io/metadata.name: baseline-afie
    name: baseline-afie
    resourceVersion: "1421"
    uid: 1ec70ade-782f-4726-8c81-ef8e3783ec53
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-07-01T10:03:32Z"
    labels:
      kubernetes.io/metadata.name: baseline-manual
    name: baseline-manual
    resourceVersion: "1412"
    uid: 1d599951-d8ba-4a15-bcf8-a95bcb80514f
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-07-01T10:03:32Z"
    labels:
      kubernetes.io/metadata.name: baseline-threshold
    name: baseline-threshold
    resourceVersion: "1418"
    uid: dfa02091-e6e1-4ded-9097-a61e57d81022
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-07-01T10:03:32Z"
    labels:
      kubernetes.io/metadata.name: baseline-vpa
    name: baseline-vpa
    resourceVersion: "1415"
    uid: 6cf2f13d-2f23-4687-bad5-d768d6f7d377
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-07-01T09:52:33Z"
    labels:
      kubernetes.io/metadata.name: default
    name: default
    resourceVersion: "7"
    uid: b621da40-3995-41e2-afac-00b4da9c9052
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-07-01T09:52:33Z"
    labels:
      kubernetes.io/metadata.name: kube-node-lease
    name: kube-node-lease
    resourceVersion: "11"
    uid: a19a07dd-9c95-4c4c-9bb5-7ee5fb294ca9
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-07-01T09:52:33Z"
    labels:
      kubernetes.io/metadata.name: kube-public
    name: kube-public
    resourceVersion: "5"
    uid: bcae0c56-d4b0-46a4-a62e-662b18ef1578
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-07-01T09:52:33Z"
    labels:
      kubernetes.io/metadata.name: kube-system
    name: kube-system
    resourceVersion: "3"
    uid: 557dcb2c-f2b7-4cb9-84a2-e8895e2406fd
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"local-path-storage"}}
    creationTimestamp: "2026-07-01T09:52:40Z"
    labels:
      kubernetes.io/metadata.name: local-path-storage
    name: local-path-storage
    resourceVersion: "333"
    uid: b0d41857-a680-47f3-8db0-413c58fe83c3
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-07-01T10:03:32Z"
    labels:
      kubernetes.io/metadata.name: monitoring
    name: monitoring
    resourceVersion: "1406"
    uid: c5c64be8-f200-4446-b3b6-792da9fa051a
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
kind: List
metadata:
  resourceVersion: ""
